### YamlMime:UniversalReference
items:
  - uid: Google::Cloud::Vision::V1::OutputConfig
    children: 
      - Google::Cloud::Vision::V1::OutputConfig#gcs_destination
      - Google::Cloud::Vision::V1::OutputConfig#batch_size
    fullName: Google::Cloud::Vision::V1::OutputConfig
    langs:
      - ruby
    module: google-cloud-vision-v1
    id: OutputConfig
    summary: "The desired output location and metadata."
    type: 'class'
  - uid: Google::Cloud::Vision::V1::OutputConfig#gcs_destination
    fullName: Google::Cloud::Vision::V1::OutputConfig#gcs_destination
    name: gcs_destination
    langs:
      - ruby
    module: google-cloud-vision-v1
    id: gcs_destination
    summary: ""
    type: method
    syntax:
      description: ""
      content: "#gcs_destination => ::Google::Cloud::Vision::V1::GcsDestination"
      parameters:
        []
      return:
          type:
            - "::Google::Cloud::Vision::V1::GcsDestination"
          description: "The Google Cloud Storage location to write the output(s) to."
  - uid: Google::Cloud::Vision::V1::OutputConfig#gcs_destination=
    fullName: Google::Cloud::Vision::V1::OutputConfig#gcs_destination=
    name: gcs_destination=
    langs:
      - ruby
    module: google-cloud-vision-v1
    id: gcs_destination=
    summary: ""
    type: method
    syntax:
      description: ""
      content: "#gcs_destination= => ::Google::Cloud::Vision::V1::GcsDestination"
      parameters:
        []
      return:
          type:
            - "::Google::Cloud::Vision::V1::GcsDestination"
          description: "The Google Cloud Storage location to write the output(s) to."
  - uid: Google::Cloud::Vision::V1::OutputConfig#batch_size
    fullName: Google::Cloud::Vision::V1::OutputConfig#batch_size
    name: batch_size
    langs:
      - ruby
    module: google-cloud-vision-v1
    id: batch_size
    summary: ""
    type: method
    syntax:
      description: ""
      content: "#batch_size => ::Integer"
      parameters:
        []
      return:
          type:
            - "::Integer"
          description: "The max number of response protos to put into each output JSON file on
Google Cloud Storage.
The valid range is [1, 100]. If not specified, the default value is 20.

For example, for one pdf file with 100 pages, 100 response protos will
be generated. If `batch_size` = 20, then 5 json files each
containing 20 response protos will be written under the prefix
`gcs_destination`.`uri`.

Currently, batch_size only applies to GcsDestination, with potential future
support for other output configurations."
  - uid: Google::Cloud::Vision::V1::OutputConfig#batch_size=
    fullName: Google::Cloud::Vision::V1::OutputConfig#batch_size=
    name: batch_size=
    langs:
      - ruby
    module: google-cloud-vision-v1
    id: batch_size=
    summary: ""
    type: method
    syntax:
      description: ""
      content: "#batch_size= => ::Integer"
      parameters:
        []
      return:
          type:
            - "::Integer"
          description: "The max number of response protos to put into each output JSON file on
Google Cloud Storage.
The valid range is [1, 100]. If not specified, the default value is 20.

For example, for one pdf file with 100 pages, 100 response protos will
be generated. If `batch_size` = 20, then 5 json files each
containing 20 response protos will be written under the prefix
`gcs_destination`.`uri`.

Currently, batch_size only applies to GcsDestination, with potential future
support for other output configurations."
references: []
